[package]
name = "project-models"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20.3"
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"

[dev-dependencies]
tempfile = "3.17.1"
