[clickhouse]
url = "127.0.0.1:9000"
user = "admin"
password = "securepass"
database = "test_db"

[redis]
host = "127.0.0.1"
port = 6379
read_user = "readonly_user"
read_password = "readonlypass"
write_user = "write_user"
write_password = "writepass"
api_db = "1"
greeks_db = "2"
futures_db = "3"
index_db = "4"

[kafka]
broker = "kafka_broker"
tick_data_topic = "kafka_topic"

[zerodha]
api_key = "default_api_key"
api_secret = "default_api_secret"
user_name = "default_user"

